CFLAGS += -DBOARD_VERIRADIO=1
CFLAGS += -DBACKDOOR_IOID=0x00000000

CONTIKI_TARGET_DIRS += veriradio common

BOARD_SOURCEFILES += sensortag-sensors.c  sensor-common.c
BOARD_SOURCEFILES += hdc-1000-sensor.c button-sensor.c
BOARD_SOURCEFILES += ext-flash.c
BOARD_SOURCEFILES += board.c board-spi.c board-i2c.c
